import "styles/global_style.css"
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Providers from "./Providers"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <Providers>

      <html lang="en">
        <body className={inter.className}>
          <div className="flex">

            {/* <aside className="bg-[#282A2A]">
            <Sidebar selection={null}/>
          </aside> */}
            {children}
          </div>
        </body>
      </html >
    </Providers>
  )
}
